name: Create Taskora Signing Key

on:
  workflow_dispatch:

jobs:
  create-key:
    runs-on: ubuntu-latest

    steps:
      - name: Create signing key
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          keytool -genkeypair -v \
            -keystore taskora-release.jks \
            -alias taskora \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$STORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=Taskora, OU=Taskora, O=Taskora, L=Sanaa, ST=Yemen, C=YE"

      - name: Create Base64
        run: |
          base64 -w 0 taskora-release.jks > KEYSTORE_BASE64.txt

      - name: Upload signing key
        uses: actions/upload-artifact@v4
        with:
          name: taskora-signing-key
          path: |
            taskora-release.jks
            KEYSTORE_BASE64.txt
